version: '3.9'
services:
  api:
    build:
      context: ./api
      target: dev
    command: npm run start:dev
    ports:
      - "8080:8080"
    environment:
      NODE_ENV: development
      DEBUG: nodejs-docker-express:*
  graphdb:
    container_name: graphdb
    image: khaller/graphdb-free:9.10.0
    ports:
      - "7200:7200"
    build:
      context: ./bd
      dockerfile: ./Dockerfile
    restart: always
